import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Photocontest',
  description: 'Generated by human',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}): any {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
